name: deployment
on:
  push:
    branches:
      - master

jobs:
  Bridge-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Build application
        working-directory: .
        run: |
          ls
          npm install
          CI= npm run build
          ls
          mv build ../backend/ 